export  const MESSAGE_TYPE = "MESSAGE_TYPE"
export const CONNECTION_TYPE = "CONNECTION_TYPE"
export const SHARE_TYPE = "SHARE_TYPE"
export const CONNECTED_STATUS = 'CONNECTED_STATUS'
export const DISCONNECTED_STATUS = 'DISCONNECTED_STATUS'